### PR TITLE
Specimen resource

### PR DESCRIPTION
**Pull request by mariusnaude**

### CODE REVIEW

**Comment by Xhanti2309** [comment]
Make sure the ValueSet for this code ($SCT#395058002) is defined in the terminology file.

Is there a need for identifier in this profile?

**Comment by Xhanti2309** [comment]
DiagnosticReport - Profiles - must include encounter data element.

Task - Profiles - requester and owner data elements must have cardinality specified or have a reference specified.

ServiceRequest - Profiles - doNotPerform data element must be listed under intent data element as per the base profile.

**Comment by rmrlangford** [comment]
> ($SCT#395058002 is in the valueset VSSpecimenType

**Comment by rmrlangford** [comment]
> 

Ahh thanks, fixed diagnostic report and Task :) 

However, doNotPerform is a standalone element in the root of ServiceRequest

**Pull request merged**
